In [2]:
import numpy as np


In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a=np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [8]:
a=np.array([1,2,3],dtype=str)
a

array(['1', '2', '3'], dtype='<U1')

In [11]:
a=np.array([2,3,4],dtype=bool)
a

array([ True,  True,  True])

In [4]:
a=np.array([0,2,3,4],dtype=bool)
a

array([False,  True,  True,  True])

In [13]:
a=np.array([2,3,4],dtype=complex)
a

array([2.+0.j, 3.+0.j, 4.+0.j])

In [19]:
a=a.reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [16]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a=np.ones((2,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.random.random((3,4))# first rsndom is class and second is  function

array([[0.99550511, 0.16160769, 0.19576802, 0.40428254],
       [0.45372138, 0.52233427, 0.54049492, 0.02204365],
       [0.10491378, 0.7678267 , 0.16068148, 0.03110828]])

In [9]:
np.linspace(-10,10,10) #(lower range ,uper range,number of item you want to insert) it generates all number with sane range.

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
#ndim : number of dimension
a.ndim

2

In [14]:
a.shape

(2, 5)

In [15]:
a.size

10

In [16]:
a.itemsize

8

In [17]:
a.dtype

dtype('float64')

In [18]:
a.astype(np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [ ]:
#0: columns,1: rows

In [8]:
np.log(a)

array([-inf,   0.,   0.,   0.], dtype=float16)

In [7]:
import warnings
warnings.filterwarnings("ignore")

In [9]:
np.exp(a)

array([1.   , 2.719, 2.719, 2.719], dtype=float16)

In [17]:
b=np.random.random((3,6))
b=b.astype(np.float)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
np.floor(b)